In [ ]:
#last update 06121616
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import os
path="/content/drive/MyDrive/ml-latest-small"
os.chdir(path)
os.listdir(path)

['ratings.csv', 'tags.csv', 'movies.csv', 'links.csv', 'README.txt']

In [ ]:
import numpy as np

In [ ]:
import csv
tagscsv_list = list(csv.reader(open("tags.csv")))
tagscsv_nparray=np.array(tagscsv_list)
print(tagscsv_nparray)
print(tagscsv_nparray.shape)
'''
user_num_tag=int(tagscsv_nparray[tagscsv_nparray.shape[0]-1][0])
user_num=user_num_tag
print(user_num)
'''

[['userId' 'movieId' 'tag' 'timestamp']
 ['2' '60756' 'funny' '1445714994']
 ['2' '60756' 'Highly quotable' '1445714996']
 ...
 ['610' '3265' 'gun fu' '1493843984']
 ['610' '3265' 'heroic bloodshed' '1493843978']
 ['610' '168248' 'Heroic Bloodshed' '1493844270']]
(3684, 4)


'\nuser_num_tag=int(tagscsv_nparray[tagscsv_nparray.shape[0]-1][0])\nuser_num=user_num_tag\nprint(user_num)\n'

In [ ]:
'''
moviescsv_list = list(csv.reader(open("movies.csv")))
moviescsv_nparray=np.array(moviescsv_list)
print(moviescsv_nparray)
print(moviescsv_nparray.shape)
'''
movie_dict={}
for i in range(1,tagscsv_nparray.shape[0]):
  movie_dict[tagscsv_nparray[i][1]]=movie_dict.get(tagscsv_nparray[i][1],0)+1
movie_list=list(movie_dict)
print(movie_list)
movie_nparray=np.array(movie_list)
print(movie_nparray.shape)
movie_num=len(movie_list)
movie_num

['60756', '89774', '106782', '48516', '431', '1221', '5995', '44665', '52604', '88094', '144210', '1569', '118985', '119141', '109487', '2', '110', '410', '2023', '2124', '2953', '3114', '3578', '4223', '5388', '6058', '6534', '6541', '6564', '7153', '8641', '27660', '27706', '27808', '27831', '31658', '33162', '34150', '37729', '38061', '45447', '46723', '46972', '46976', '49130', '49530', '53464', '58047', '59501', '60074', '60126', '61024', '63992', '68848', '71535', '87430', '88405', '96861', '99114', '103042', '104863', '107348', '108190', '111743', '114180', '115149', '116897', '122912', '128360', '135133', '135518', '135536', '136864', '139385', '158966', '168248', '174053', '179401', '183611', '184471', '187593', '187595', '260', '296', '4896', '106489', '101142', '115617', '120635', '1726', '2387', '3052', '5088', '7022', '7254', '8957', '9010', '42632', '58301', '60950', '62434', '67695', '100083', '156371', '158872', '3556', '6323', '6367', '59103', '52287', '293', '54286', 

1572

In [ ]:
tag_dict={}
for i in range(1,tagscsv_nparray.shape[0]):
  tag_dict[tagscsv_nparray[i][2]]=tag_dict.get(tagscsv_nparray[i][2],{})
  tag_dict[tagscsv_nparray[i][2]][tagscsv_nparray[i][1]]=tag_dict[tagscsv_nparray[i][2]].get(tagscsv_nparray[i][1],0)+1
tag_list=list(tag_dict)
tag_num=len(tag_list)
print(tag_dict)
print(tag_list)
tag_num

{'funny': {'60756': 3, '2953': 1, '3114': 1, '68848': 1, '71535': 1, '88405': 1, '99114': 1, '119141': 1, '179401': 1, '183611': 1, '101142': 1, '126548': 1, '39': 1, '69122': 1, '106766': 1, '112852': 1, '134170': 1, '148626': 1, '167746': 1, '296': 1, '1732': 1}, 'Highly quotable': {'60756': 1, '296': 1, '1732': 1}, 'will ferrell': {'60756': 3, '107348': 1}, 'Boxing story': {'89774': 1}, 'MMA': {'89774': 1}, 'Tom Hardy': {'89774': 1, '27831': 1}, 'drugs': {'106782': 1, '4034': 1, '296': 2, '27020': 1, '1953': 1, '6002': 1, '8645': 1, '57669': 1, '1732': 1}, 'Leonardo DiCaprio': {'106782': 1, '49530': 1, '99114': 1, '1059': 1, '48516': 2, '147': 1, '74458': 1, '79132': 1, '5989': 1}, 'Martin Scorsese': {'106782': 1, '1343': 1, '48516': 1, '74458': 1}, 'way too long': {'48516': 1}, 'Al Pacino': {'431': 1, '1221': 1, '2023': 1, '5388': 1, '4262': 1}, 'gangster': {'431': 1, '296': 1}, 'mafia': {'431': 1, '2023': 1, '55765': 1}, 'Mafia': {'1221': 2, '16': 1, '858': 1, '1213': 1, '1245': 1

1589

In [ ]:
count_list_2d_tagnum_movienum=[]
for i in range(tag_num):
  t=[]
  for j in range(movie_num):
    t_dict=tag_dict.get(tag_list[i],{})
    n=t_dict.get(movie_list[j],0)
    t.append(n)
  count_list_2d_tagnum_movienum.append(t)
count_nparray_2d_tagnum_movienum=np.array(count_list_2d_tagnum_movienum)
print(count_nparray_2d_tagnum_movienum)
print(count_nparray_2d_tagnum_movienum.shape)
print(np.argmin(np.amax(count_nparray_2d_tagnum_movienum,0)))
print(np.argmin(np.amax(count_nparray_2d_tagnum_movienum,1)))

[[3 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
(1589, 1572)
1
1


In [ ]:
applied_list_2d_tagnum_movienum=[[int(j>0) for j in i ]for i in count_list_2d_tagnum_movienum]
applied_nparray_2d_tagnum_movienum=np.array(applied_list_2d_tagnum_movienum)
print(applied_nparray_2d_tagnum_movienum)
print(applied_nparray_2d_tagnum_movienum.shape)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
(1589, 1572)


In [ ]:
T,S,D_t = np.linalg.svd(applied_nparray_2d_tagnum_movienum, full_matrices=0)
print(T.shape,T)
print(S.shape,S)
print(D_t.shape,D_t)

(1589, 1572) [[-9.41546752e-02 -1.69774073e-03  1.81761750e-02 ... -8.31381997e-18
  -1.39862080e-17 -9.32413868e-18]
 [-7.91855321e-02 -1.46158823e-03  2.16032441e-02 ...  6.23330304e-03
   1.00255540e-02 -6.72533000e-02]
 [-1.94214932e-03 -4.45890575e-05  2.97073319e-04 ... -6.07684676e-03
   3.04036693e-02  5.68046980e-02]
 ...
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.40571050e-03 -2.61917633e-05 -4.27473565e-04 ...  1.11643758e-01
  -2.91337994e-02 -3.46939422e-02]]
(1572,) [1.36414323e+01 1.14640652e+01 8.82036587e+00 ... 8.18256254e-17
 5.94330503e-17 6.74868540e-18]
(1572, 1572) [[-1.95434099e-02 -6.20138161e-05 -7.30285917e-03 ... -4.03299543e-06
   0.00000000e+00  0.00000000e+00]
 [-3.92067474e-04 -1.89565886e-06 -8.78823463e-05 ...  6.16029267e-06
   0.00000000e+00  0.00000000e+00]
 [ 3.59326236e-03  8.14

In [ ]:
S_rate=[1]
for i in range(1,len(S)):
  if S[i-1]>0:
    S_rate.append(S[i]/S[i-1])
S_num=len(S)
i=1
while i<len(S_rate):
  if S_rate[i]/S_rate[i-1]<0.001:
    S_num=i
    break
  i=i+1
print(S_num,S[S_num-1],S[S_num])

947 0.16618125685718224 1.1588360650098707e-14


In [ ]:
T_delete=np.delete(T,np.s_[S_num:],1)
print(T_delete.shape)
'''
S_delete=np.delete(S,np.s_[S_num:])
S1_delete=1/S_delete
S1_delete=np.diag(S1_delete)
S1_delete
print(S1_delete.shape)
'''

(1589, 947)


'\nS_delete=np.delete(S,np.s_[S_num:])\nS1_delete=1/S_delete\nS1_delete=np.diag(S1_delete)\nS1_delete\nprint(S1_delete.shape)\n'

In [ ]:
dt_nparray_2d_t=np.identity(tag_num)
di_nparray_2d_t=np.transpose(applied_list_2d_tagnum_movienum)
dt1_nparray_2d_t=dt_nparray_2d_t.dot(T_delete) #.dot(S1_delete)
di1_nparray_2d_t=di_nparray_2d_t.dot(T_delete) #.dot(S1_delete)
print(dt1_nparray_2d_t.shape)
print(di1_nparray_2d_t.shape)
print(np.linalg.norm(dt1_nparray_2d_t[t]))
dt1_norm_list=[np.linalg.norm(dt1_nparray_2d_t[t]) for t in range(dt1_nparray_2d_t.shape[0])]
di1_norm_list=[np.linalg.norm(di1_nparray_2d_t[i]) for i in range(di1_nparray_2d_t.shape[0])]
print(len(dt1_norm_list),min(dt1_norm_list))
print(max(di1_nparray_2d_t[3]),di1_norm_list[3])

(1589, 947)
(1572, 947)
39.64378896601239
1589 0.09258263638435626
0.8999491852092357 2.82842712474619


In [ ]:
a_is_zero=[0]
b_is_zero=[0]
def sim(a,b,a_is_zero,b_is_zero):
  if np.linalg.norm(a)==0:
    a_is_zero[0]=a_is_zero[0]+1
    return 0
  if np.linalg.norm(b)==0:
    b_is_zero[0]=b_is_zero[0]+1
    return 0
  return a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
lsi_sim_list_2d_tagnum_movienum=[[sim(dt1_nparray_2d_t[t],di1_nparray_2d_t[i],a_is_zero,b_is_zero) for i in range(movie_num)]for t in range(tag_num)]
lsi_sim_nparray_2d_tagnum_movienum=np.array(lsi_sim_list_2d_tagnum_movienum)
print(lsi_sim_nparray_2d_tagnum_movienum.shape)
print(a_is_zero[0],b_is_zero[0])

(1589, 1572)
0 0


In [ ]:
k=5
while 1:
  inp1=input("movidId(int):")
  movie_idx_nparray=np.where(movie_nparray==inp1)[0]
  print(movie_idx_nparray)
  if len(movie_idx_nparray)>0:
    break
  print('not in dataset')

movie_idx=movie_idx_nparray[0]
inp2=int(input("you like?(1 for like or 0 for false):"))
lsi_sim_list_2d_tagnum_movienum_t=np.transpose(lsi_sim_list_2d_tagnum_movienum)
#print(movie_idx,lsi_sim_list_2d_tagnum_movienum_t[movie_idx])

movie_distance_dict={}
for i in range(movie_num):
  d=np.linalg.norm(lsi_sim_list_2d_tagnum_movienum_t[i]-lsi_sim_list_2d_tagnum_movienum_t[movie_idx])
  movie_distance_dict[d]=movie_distance_dict.get(d,[])+[i]
movie_distance_list=sorted(list(movie_distance_dict))
#print(movie_distance_list)
if inp2:
  for i in range(k):
    print("distance:",movie_distance_list[i],'movieId',[movie_nparray[idx] for idx in movie_distance_dict[movie_distance_list[i]]])
else:
  print("distance:",'\t','movieId')
  for i in range(-1,-k-1,-1):
    print(movie_distance_list[i],'\t',[movie_nparray[idx] for idx in movie_distance_dict[movie_distance_list[i]]])

movidId(int):6
[]
not in dataset
movidId(int):6
[]
not in dataset
movidId(int):7
[259]
you like?(1 for like or 0 for false):0
distance: 	 movieId
8.290031288728644 	 ['296']
3.3604432226144536 	 ['924']
3.104954406478007 	 ['122912']
3.097016922411432 	 ['135536']
2.879351231501801 	 ['2959']


In [ ]:
list(range(0-1,-5-1,-1))

[-1, -2, -3, -4, -5]